### ISSUE TITLE
Code parser for csv to df

### ISSUE THREAD

**Issue by mgutierrezc** [mgutierrezc/sms_api_sender#2]
You will receive a csv with this structure: 

| Nombre | Nro | Parametro |
|--------|-----|-----------|
|        |     |           |
|        |     |           |

The parser should generate a panda df where all the variables are string

**Comment by mgutierrezc** [comment]
@Sweetdreamstome, no cerremos el issue directamente. Cuando cerremos el pull req #3 , se cerrara automaticamente el issue

**Comment by mgutierrezc** [comment]
@Sweetdreamstome if "Nro" is the only column on the file, create the columns "Nombre" and "Parametro". Their values should be ""

**Comment by Sweetdreamstome** [comment]
> @Sweetdreamstome if "Nro" is the only column on the file, create the columns "Nombre" and "Parametro". Their values should be ""

@mgutierrezc una consulta, ese csv solo tendria una columna? o existen más columnas en el csv?

**Comment by mgutierrezc** [comment]
> > @Sweetdreamstome if "Nro" is the only column on the file, create the columns "Nombre" and "Parametro". Their values should be ""
> 
> @mgutierrezc una consulta, ese csv solo tendria una columna? o existen más columnas en el csv?

Puede tener una o 3. Prepara el código para ambos casos

**Comment by mgutierrezc** [comment]
@Sweetdreamstome
